version: "3.8"

services:
  raft-rds:
    image: ghcr.io/franzfischer78/raftmodding-rds:latest
    container_name: raft_rds
    restart: unless-stopped

    environment:
      # What to do on startup: update & then run
      - STARTUP=updateboth

      # Filled in via Portainer env vars
      - STEAM_USER=${STEAM_USER}
      - STEAM_PASS=${STEAM_PASS}
      # Optional Steam Guard email code
      # - STEAM_AUTH=${STEAM_AUTH}

    volumes:
      # WSL2 path we created
      - /srv/raft-rds:/home/container

    ports:
      # HOST:CONTAINER (UDP)
      # Host 27515 → container 27015
      # Host 27520 → container 27020
      - "27515:27015/udp"
      - "27520:27020/udp"

  rds-panel:
    image: node:20-alpine
    container_name: rds_panel
    restart: unless-stopped

    working_dir: /app/panel

    environment:
      # Set this via Portainer env vars (ADMIN_TOKEN)
      - ADMIN_TOKEN=${ADMIN_TOKEN}

    command: >
      sh -c "
        apk add --no-cache git &&
        mkdir -p /app &&
        if [ ! -d /app/.git ]; then
          git clone https://github.com/makeouthillx32/RDS-Beta-Docker-Image.git /app;
        fi &&
        cd /app/panel &&
        npm install &&
        node server.js
      "

    volumes:
      # So panel can control raft_rds via Docker API
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      # Web panel on host 8899 → container 3000
      - "8899:3000"
